CREATE DATABASE  IF NOT EXISTS `tt_agentic` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `tt_agentic`;
-- MySQL dump 10.13  Distrib 8.0.42, for Win64 (x86_64)
--
-- Host: localhost    Database: tt_agentic
-- ------------------------------------------------------
-- Server version	8.0.42

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `api_provider_endpoint_parameter_cfg`
--

DROP TABLE IF EXISTS `api_provider_endpoint_parameter_cfg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `api_provider_endpoint_parameter_cfg` (
  `cfg_id` int NOT NULL AUTO_INCREMENT,
  `endpoint_id` int NOT NULL,
  `object_type` enum('FLIGHT','HOTEL','PACKAGE') NOT NULL DEFAULT 'FLIGHT',
  `parameter_role` varchar(30) NOT NULL,
  `is_active` enum('Y','N') NOT NULL DEFAULT 'Y',
  `ui_section` varchar(50) NOT NULL,
  `ui_control_type` enum('TEXT','DATE','SELECT','NUMBER','CHECKBOX','HIDDEN') DEFAULT NULL,
  `ui_label` varchar(120) DEFAULT NULL,
  `ui_placeholder` varchar(200) DEFAULT NULL,
  `ui_help_text` varchar(500) DEFAULT NULL,
  `ui_order` int DEFAULT NULL,
  `ui_visible` enum('Y','N') DEFAULT 'Y',
  `ui_readonly` enum('Y','N') DEFAULT 'N',
  `is_required` enum('Y','N') DEFAULT 'N',
  `data_type` enum('STRING','INT','DECIMAL','DATE','DATETIME','BOOL') DEFAULT NULL,
  `min_value` decimal(18,6) DEFAULT NULL,
  `max_value` decimal(18,6) DEFAULT NULL,
  `min_len` int DEFAULT NULL,
  `max_len` int DEFAULT NULL,
  `regex_rule` varchar(255) DEFAULT NULL,
  `default_value` varchar(255) DEFAULT NULL,
  `send_if_empty` enum('Y','N') DEFAULT 'N',
  `allowed_values_csv` varchar(1000) DEFAULT NULL,
  `lov_source_type` enum('STATIC','SQL','API') DEFAULT NULL,
  `lov_source_sql` varchar(2000) DEFAULT NULL,
  `lov_endpoint_id` int DEFAULT NULL,
  `provider_parameter_name` varchar(80) DEFAULT NULL,
  `request_json_path` varchar(255) DEFAULT NULL,
  `value_source_type` varchar(50) DEFAULT NULL,
  `value_source_key` varchar(100) DEFAULT NULL,
  `transform_rule` varchar(80) DEFAULT NULL,
  `response_json_path` varchar(255) DEFAULT NULL,
  `row_key_group` varchar(30) DEFAULT NULL,
  `is_result_identifier` enum('Y','N') DEFAULT 'N',
  `display_in_results` enum('Y','N') DEFAULT 'N',
  `display_in_summary` enum('Y','N') DEFAULT 'N',
  `display_in_itinerary` enum('Y','N') DEFAULT 'N',
  `display_in_trace` enum('Y','N') DEFAULT 'Y',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `developer_notes` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`cfg_id`),
  KEY `ix_cfg_endpoint_role` (`endpoint_id`,`parameter_role`,`is_active`),
  KEY `ix_cfg_ui` (`endpoint_id`,`ui_section`,`ui_order`),
  KEY `ix_cfg_lov` (`lov_source_type`,`lov_endpoint_id`),
  CONSTRAINT `fk_cfg_endpoint` FOREIGN KEY (`endpoint_id`) REFERENCES `api_provider_endpoint` (`endpoint_id`)
) ENGINE=InnoDB AUTO_INCREMENT=93 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `api_provider_endpoint_parameter_cfg`
--

/*!40000 ALTER TABLE `api_provider_endpoint_parameter_cfg` DISABLE KEYS */;
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (24,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','SELECT','From Airport','Select departure airport',NULL,10,'Y','N','Y','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,'SQL','SELECT airport_code AS value, CONCAT(airport_code, \" - \", airport_name) AS label FROM tt_agentic.airport ORDER BY airport_code',NULL,'from_airport','search.from_airport',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-02-24 14:50:10','Default BOM only for testing. Change anytime.');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (25,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','SELECT','To Airport','Select arrival airport',NULL,20,'Y','N','Y','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,'SQL','SELECT airport_code AS value, CONCAT(airport_code, \" - \", airport_name) AS label FROM tt_agentic.airport ORDER BY airport_code',NULL,'to_airport','search.to_airport',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-02-24 14:50:10','Default DOH only for testing.');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (26,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','DATE','Depart Date','YYYY-MM-DD',NULL,30,'Y','N','Y','DATE',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,'depart_date','search.depart_date',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-02-24 14:50:10','Default 2026-04-01 only for testing.');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (27,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','SELECT','Cabin Class','Select cabin class','Economy/Business/etc.',40,'Y','N','Y','STRING',NULL,NULL,NULL,NULL,NULL,'','N','Economy,Premium Economy,Business,First','STATIC',NULL,NULL,'cabin_class','search.cabin_class',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-02-24 14:50:10',NULL);
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (28,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','SELECT','Preferred Airline','Optional','Leave blank to allow all airlines.',50,'Y','N','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,'SQL','SELECT airline_code AS value, CONCAT(airline_code, \" - \", airline_name) AS label FROM tt_agentic.airline ORDER BY airline_code',NULL,'preferred_airline','search.preferred_airline',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-02-24 14:50:10',NULL);
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (29,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','SELECT','Currency','Select currency','Currency for pricing display.',60,'Y','N','Y','STRING',NULL,NULL,NULL,NULL,NULL,'INR','N',NULL,'SQL','SELECT CURRENCY_CODE AS value, CONCAT(CURRENCY_CODE, \" - \", CURRENCY_NAME) AS label FROM tt_agentic.currency_mst ORDER BY CURRENCY_CODE',NULL,'currency','search.currency',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-02-24 14:50:10','Default INR only for testing.');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (30,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','NUMBER','Top N Result','How many rows?','Limits results returned by provider.',70,'Y','N','Y','INT',NULL,NULL,NULL,NULL,NULL,'100','N',NULL,NULL,NULL,NULL,'top_n','search.top_n',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-02-24 11:50:10','Default 5 only for testing.');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (31,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','NUMBER','Include +/- Days','Days around depart date','If 2, provider checks 2 days before and after.',80,'Y','N','Y','INT',NULL,NULL,NULL,NULL,NULL,'0','N',NULL,NULL,NULL,NULL,'include_days','search.include_days',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-02-24 11:50:10','Default 2 only for testing.');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (47,1,'FLIGHT','RESPONSE','Y','RESULT_GRID','TEXT','Flight No',NULL,NULL,10,'Y','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','flight_number',NULL,'results[].flight.flight_number',NULL,'N','Y','N','N','Y','2026-02-24 17:31:16','Grid column: flight number');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (48,1,'FLIGHT','RESPONSE','Y','RESULT_GRID','TEXT','Airline',NULL,NULL,20,'Y','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','airline_name',NULL,'results[].flight.airline.name',NULL,'N','Y','N','N','Y','2026-02-24 17:31:16','Grid column: airline name');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (49,1,'FLIGHT','RESPONSE','Y','RESULT_GRID','TEXT','From',NULL,NULL,30,'Y','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','from_airport',NULL,'results[].flight.route.from.airport',NULL,'N','Y','N','N','Y','2026-02-24 17:31:16','Grid column: from airport');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (50,1,'FLIGHT','RESPONSE','Y','RESULT_GRID','TEXT','To',NULL,NULL,40,'Y','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','to_airport',NULL,'results[].flight.route.to.airport',NULL,'N','Y','N','N','Y','2026-02-24 17:31:16','Grid column: to airport');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (51,1,'FLIGHT','RESPONSE','Y','RESULT_GRID','TEXT','Departure',NULL,NULL,50,'Y','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','scheduled_departure',NULL,'results[].flight.schedule.scheduled_departure_formatted',NULL,'N','Y','N','N','Y','2026-02-24 17:31:16','Grid column: scheduled departure formatted');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (52,1,'FLIGHT','RESPONSE','Y','RESULT_GRID','TEXT','Arrival',NULL,NULL,60,'Y','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','scheduled_arrival',NULL,'results[].flight.schedule.scheduled_arrival_formatted',NULL,'N','Y','N','N','Y','2026-02-24 17:31:16','Grid column: scheduled arrival formatted');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (53,1,'FLIGHT','RESPONSE','Y','RESULT_GRID','TEXT','Total',NULL,NULL,70,'Y','Y','N','DECIMAL',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','total_price',NULL,'results[].fare.price.total',NULL,'N','Y','N','N','Y','2026-02-24 17:31:16','Grid column: total price');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (54,1,'FLIGHT','RESPONSE','Y','RESULT_GRID','TEXT','Currency',NULL,NULL,80,'Y','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','currency',NULL,'results[].fare.price.currency',NULL,'N','Y','N','N','Y','2026-02-24 17:31:16','Grid column: currency');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (55,1,'FLIGHT','RESPONSE','Y','RESULT_GRID','TEXT','Refundable',NULL,NULL,90,'Y','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','refundable',NULL,'results[].fare.flags.refundable_formatted',NULL,'N','Y','N','N','Y','2026-02-24 17:31:16','Grid column: refundable formatted');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (56,1,'FLIGHT','RESPONSE','Y','RESULT_GRID','TEXT','Changeable',NULL,NULL,100,'Y','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','changeable',NULL,'results[].fare.flags.changeable_formatted',NULL,'N','Y','N','N','Y','2026-02-24 17:31:16','Grid column: changeable formatted');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (57,1,'FLIGHT','RESULT_KEY','Y','RESULT_KEY','HIDDEN','',NULL,NULL,10,'N','Y','N','INT',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','row_flight_id',NULL,'results[].row_key.flight_id','ROWKEY','Y','N','N','N','Y','2026-02-24 17:32:10','Row identifier: flight_id');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (58,1,'FLIGHT','RESULT_KEY','Y','RESULT_KEY','HIDDEN','',NULL,NULL,20,'N','Y','N','INT',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','row_fare_id',NULL,'results[].row_key.fare_id','ROWKEY','Y','N','N','N','Y','2026-02-24 17:32:10','Row identifier: fare_id');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (59,1,'FLIGHT','RESULT_KEY','Y','RESULT_KEY','HIDDEN','',NULL,NULL,30,'N','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','row_flight_number',NULL,'results[].row_key.flight_number','ROWKEY','Y','N','N','N','Y','2026-02-24 17:32:10','Row identifier: flight_number');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (60,1,'FLIGHT','RESULT_KEY','Y','RESULT_KEY','HIDDEN','',NULL,NULL,40,'N','Y','N','DATETIME',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,'SEARCH_RESULT','row_scheduled_departure',NULL,'results[].row_key.scheduled_departure','ROWKEY','Y','N','N','N','Y','2026-02-24 17:32:10','Row identifier: scheduled_departure raw');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (61,2,'FLIGHT','REQUEST','Y','BOOK_FORM','HIDDEN','agent_fsr_id',NULL,NULL,10,'N','Y','Y','INT',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,'agent_fsr_id','booking.agent_fsr_id','CONTEXT','agent_fsr_id',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 18:59:17','Selected search result identity (from confirm/results post)');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (62,2,'FLIGHT','REQUEST','Y','BOOK_FORM','NUMBER','Infants','0','Number of infant passengers',40,'Y','N','N','INT',0.000000,9.000000,NULL,NULL,NULL,'0','N',NULL,NULL,NULL,NULL,'infants','booking.pax_counts.infants',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:01:11','Optional');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (64,2,'FLIGHT','REQUEST','Y','BOOK_FORM','NUMBER','Adults','1','Number of adult passengers',20,'Y','N','Y','INT',1.000000,9.000000,NULL,NULL,NULL,'1','N',NULL,NULL,NULL,NULL,'adults','booking.pax_counts.adults',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:25','Booking passenger count');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (65,2,'FLIGHT','REQUEST','Y','BOOK_FORM','NUMBER','Children','0','Number of child passengers',30,'Y','N','N','INT',0.000000,9.000000,NULL,NULL,NULL,'0','N',NULL,NULL,NULL,NULL,'children','booking.pax_counts.children',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:25','Optional');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (67,2,'FLIGHT','REQUEST','Y','BOOK_FORM','TEXT','Email','name@example.com','Booking confirmation will be sent here',60,'Y','N','N','STRING',NULL,NULL,NULL,NULL,NULL,'','N',NULL,NULL,NULL,NULL,'email','booking.passenger.email','TRAVELLER','email',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:25','Prefill from user profile, allow edit');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (68,2,'FLIGHT','REQUEST','Y','BOOK_FORM','TEXT','Mobile','+973xxxxxxxx','Phone number for alerts',70,'Y','N','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,'phone','booking.passenger.phone','TRAVELLER','phone',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:25','Optional');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (69,2,'FLIGHT','REQUEST','Y','BOOK_FORM','TEXT','First Name',NULL,NULL,90,'Y','N','Y','STRING',NULL,NULL,NULL,NULL,NULL,'','N',NULL,NULL,NULL,NULL,'first_name','booking.passenger.first_name','TRAVELLER','first_name',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:25','Prefill from profile');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (70,2,'FLIGHT','REQUEST','Y','BOOK_FORM','TEXT','Last Name',NULL,NULL,100,'Y','N','Y','STRING',NULL,NULL,NULL,NULL,NULL,'','N',NULL,NULL,NULL,NULL,'last_name','booking.passenger.last_name','TRAVELLER','last_name',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:25','Prefill from profile');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (71,2,'FLIGHT','REQUEST','Y','BOOK_FORM','DATE','Date of Birth',NULL,NULL,110,'Y','N','Y','DATE',NULL,NULL,NULL,NULL,NULL,'','N',NULL,NULL,NULL,NULL,'dob','booking.passenger.date_of_birth','TRAVELLER','date_of_birth',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:25','Prefill from profile');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (72,2,'FLIGHT','REQUEST','Y','BOOK_FORM','SELECT','Gender',NULL,NULL,120,'Y','N','Y','STRING',NULL,NULL,NULL,NULL,NULL,'','N','Male,Female,Other','STATIC',NULL,NULL,'gender','booking.passenger.gender','TRAVELLER','gender',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:25','Prefill from profile');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (73,2,'FLIGHT','REQUEST','Y','BOOK_FORM','TEXT','Nationality (ISO2)','IN','2-letter country code (example: IN)',130,'Y','N','Y','STRING',NULL,NULL,NULL,NULL,NULL,'','N',NULL,NULL,NULL,NULL,'nationality_iso2','booking.passenger.nationality_iso2','TRAVELLER','nationality_iso2',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:25','Prefill from profile');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (74,2,'FLIGHT','REQUEST','Y','BOOK_FORM','SELECT','Document Type',NULL,NULL,150,'Y','N','Y','STRING',NULL,NULL,NULL,NULL,NULL,'','N','Passport,Visa,National ID,Driving License','STATIC',NULL,NULL,'document_type','booking.travel_document.document_type','TRAVELLER','document_type',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:25','Prefill from primary travel doc');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (75,2,'FLIGHT','REQUEST','Y','BOOK_FORM','TEXT','Document Number',NULL,NULL,160,'Y','N','Y','STRING',NULL,NULL,NULL,NULL,NULL,'','N',NULL,NULL,NULL,NULL,'document_number','booking.travel_document.document_number','TRAVELLER','document_number',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:26','Prefill from primary travel doc');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (76,2,'FLIGHT','REQUEST','Y','BOOK_FORM','TEXT','Issuing Country (ISO2)',NULL,NULL,170,'Y','N','Y','STRING',NULL,NULL,NULL,NULL,NULL,'','N',NULL,NULL,NULL,NULL,'issuing_country_iso2','booking.travel_document.issuing_country_iso2','TRAVELLER','issuing_country_iso2',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:26','Prefill from primary travel doc');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (77,2,'FLIGHT','REQUEST','Y','BOOK_FORM','DATE','Document Expiry',NULL,NULL,180,'Y','N','Y','DATE',NULL,NULL,NULL,NULL,NULL,'','N',NULL,NULL,NULL,NULL,'expiry_date','booking.travel_document.expiry_date','TRAVELLER','expiry_date',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:26','Prefill from primary travel doc');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (78,2,'FLIGHT','REQUEST','Y','BOOK_FORM','SELECT','Seat Preference',NULL,NULL,200,'Y','N','N','STRING',NULL,NULL,NULL,NULL,NULL,'Any','N','Window,Aisle,Any','STATIC',NULL,NULL,'seat_preference','booking.preferences.seat_preference','TRAVELLER','seat_preference',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:26','Optional preference');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (79,2,'FLIGHT','REQUEST','Y','BOOK_FORM','SELECT','Meal Preference',NULL,NULL,210,'Y','N','N','STRING',NULL,NULL,NULL,NULL,NULL,'Standard','N','Standard,Vegetarian,Vegan,Halal,Kosher,Diabetic','STATIC',NULL,NULL,'meal_preference','booking.preferences.meal_preference','TRAVELLER','meal_preference',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:26','Optional preference');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (80,2,'FLIGHT','RESPONSE','Y','BOOK_CONFIRM','TEXT','Booking Ref #',NULL,NULL,10,'Y','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'booking.booking_ref',NULL,'N','N','N','N','Y','2026-02-25 19:11:28','Provider booking reference');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (81,2,'FLIGHT','RESPONSE','Y','BOOK_CONFIRM','TEXT','Booking Status',NULL,NULL,20,'Y','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'booking.status',NULL,'N','N','N','N','Y','2026-02-25 19:11:28','CONFIRMED/FAILED/PENDING');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (82,2,'FLIGHT','RESPONSE','Y','BOOK_CONFIRM','TEXT','Total Amount',NULL,NULL,30,'Y','Y','N','DECIMAL',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'booking.total_amount',NULL,'N','N','N','N','Y','2026-02-25 19:11:28','Total price');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (83,2,'FLIGHT','RESPONSE','Y','BOOK_CONFIRM','TEXT','Currency',NULL,NULL,40,'Y','Y','N','STRING',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'booking.currency',NULL,'N','N','N','N','Y','2026-02-25 19:11:28','Currency');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (84,2,'FLIGHT','REQUEST','Y','BOOK_FORM','HIDDEN','flight_id',NULL,NULL,5,'N','Y','Y','INT',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,NULL,'booking.flight_id','SELECTED_ROW','flight.flight_id',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-26 16:14:24','Derived from selected flight search result (agent_flight_search_result.response_json)');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (85,2,'FLIGHT','REQUEST','Y','BOOK_FORM','HIDDEN','fare_id',NULL,NULL,6,'N','Y','Y','INT',NULL,NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL,NULL,NULL,'','booking.fare_id','SELECTED_ROW','fare.fare_id',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-26 17:02:08','Derived from selected flight search result (agent_flight_search_result.response_json)');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (86,2,'FLIGHT','REQUEST','Y','BOOK_FORM','DATE','Document Issue Date',NULL,NULL,171,'Y','N','Y','DATE',NULL,NULL,NULL,NULL,NULL,'','N',NULL,NULL,NULL,NULL,'issue_date','booking.travel_document.issue_date','TRAVELLER','issue_date',NULL,NULL,NULL,'N','N','N','N','Y','2026-02-25 19:10:26','Prefill from primary travel doc');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (87,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','SELECT','Trip Type','Select trip type','Choose ONE_WAY or ROUND_TRIP. MULTI_CITY can be added later.',5,'Y','N','Y','STRING',NULL,NULL,NULL,NULL,NULL,'ONE_WAY','N','ONE_WAY,ROUND_TRIP','STATIC',NULL,NULL,'trip_type','search.trip_type',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-03-13 00:52:41','Step-4: visible trip type in flight search UI.');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (88,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','DATE','Return Date','YYYY-MM-DD','',35,'Y','N','N','DATE',NULL,NULL,NULL,NULL,NULL,'','N',NULL,NULL,NULL,NULL,'return_date','search.return_date',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-03-13 00:52:41','Step-4: hidden by UI JS unless ROUND_TRIP selected; server validates when ROUND_TRIP.');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (89,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','SELECT','Adults','Select adults','Number of adult passengers',45,'Y','N','Y','INT',NULL,NULL,NULL,NULL,NULL,'1','N','1,2,3,4,5,6,7,8,9','STATIC',NULL,NULL,'adults','search.adults',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-03-16 10:06:49','Search page traveller count - adults');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (90,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','SELECT','Children','Select children','Number of child passengers',46,'Y','N','N','INT',NULL,NULL,NULL,NULL,NULL,'0','N','0,1,2,3,4,5,6,7,8,9','STATIC',NULL,NULL,'children','search.children',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-03-16 10:06:59','Search page traveller count - children');
INSERT INTO `api_provider_endpoint_parameter_cfg` (`cfg_id`, `endpoint_id`, `object_type`, `parameter_role`, `is_active`, `ui_section`, `ui_control_type`, `ui_label`, `ui_placeholder`, `ui_help_text`, `ui_order`, `ui_visible`, `ui_readonly`, `is_required`, `data_type`, `min_value`, `max_value`, `min_len`, `max_len`, `regex_rule`, `default_value`, `send_if_empty`, `allowed_values_csv`, `lov_source_type`, `lov_source_sql`, `lov_endpoint_id`, `provider_parameter_name`, `request_json_path`, `value_source_type`, `value_source_key`, `transform_rule`, `response_json_path`, `row_key_group`, `is_result_identifier`, `display_in_results`, `display_in_summary`, `display_in_itinerary`, `display_in_trace`, `created_at`, `developer_notes`) VALUES (91,1,'FLIGHT','REQUEST','Y','SEARCH_FORM','SELECT','Infants','Select infants','Number of infant passengers',47,'Y','N','N','INT',NULL,NULL,NULL,NULL,NULL,'0','N','0,1,2,3,4,5,6,7,8,9','STATIC',NULL,NULL,'infants','search.infants',NULL,NULL,NULL,NULL,NULL,'N','N','N','N','Y','2026-03-16 10:07:07','Search page traveller count - infants');
/*!40000 ALTER TABLE `api_provider_endpoint_parameter_cfg` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-06-26 19:27:22
