CREATE DATABASE  IF NOT EXISTS `tt_agentic` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `tt_agentic`;
-- MySQL dump 10.13  Distrib 8.0.42, for Win64 (x86_64)
--
-- Host: localhost    Database: tt_agentic
-- ------------------------------------------------------
-- Server version	8.0.42

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `greeting_mst`
--

DROP TABLE IF EXISTS `greeting_mst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `greeting_mst` (
  `greeting_id` bigint NOT NULL AUTO_INCREMENT,
  `greeting_type` varchar(50) NOT NULL,
  `greeting_msg` varchar(500) NOT NULL,
  `greeting_key` varchar(500) GENERATED ALWAYS AS (lower(regexp_replace(coalesce(`greeting_msg`,_utf8mb4''),_utf8mb4'[^A-Za-z]',_utf8mb4''))) STORED,
  `reply_msg` varchar(1000) NOT NULL,
  `prefix_msg` varchar(1000) DEFAULT NULL,
  `suffix_msg` varchar(1000) DEFAULT NULL,
  `lang_code` varchar(20) DEFAULT 'multi',
  `display_order` int DEFAULT '1',
  `is_active` tinyint(1) DEFAULT '1',
  `remarks` varchar(500) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`greeting_id`),
  UNIQUE KEY `uk_greeting_key` (`greeting_key`)
) ENGINE=InnoDB AUTO_INCREMENT=205 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `greeting_mst`
--

/*!40000 ALTER TABLE `greeting_mst` DISABLE KEYS */;
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (1,'GENERAL','Hi','Hello!',NULL,'Please type your travel request.','multi',1,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (2,'GENERAL','Hii','Hello!',NULL,'Please type your travel request.','multi',2,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (3,'GENERAL','Hiii','Hello!',NULL,'Please type your travel request.','multi',3,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (4,'GENERAL','Hiiii','Hello!',NULL,'Please type your travel request.','multi',4,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (5,'GENERAL','Hy','Hello!',NULL,'Please type your travel request.','multi',5,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (6,'GENERAL','Hyy','Hello!',NULL,'Please type your travel request.','multi',6,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (7,'GENERAL','Hai','Hello!',NULL,'Please type your travel request.','multi',7,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (8,'GENERAL','Hay','Hello!',NULL,'Please type your travel request.','multi',8,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (9,'GENERAL','Hey','Hello!',NULL,'Please type your travel request.','multi',9,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (10,'GENERAL','Heyy','Hello!',NULL,'Please type your travel request.','multi',10,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (11,'GENERAL','Hello','Hello!',NULL,'Please type your travel request.','multi',11,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (12,'GENERAL','Helo','Hello!',NULL,'Please type your travel request.','multi',12,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (13,'GENERAL','Helloo','Hello!',NULL,'Please type your travel request.','multi',13,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (14,'GENERAL','Hellooo','Hello!',NULL,'Please type your travel request.','multi',14,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (15,'GENERAL','Hllo','Hello!',NULL,'Please type your travel request.','multi',15,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (16,'GENERAL','Hallo','Hello!',NULL,'Please type your travel request.','multi',16,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (17,'GENERAL','Halo','Hello!',NULL,'Please type your travel request.','multi',17,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (18,'GENERAL','Hola','Hello!',NULL,'Please type your travel request.','multi',18,1,'Common basic greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (19,'GENERAL','Hi there','Hello! Welcome to Smart Trip.',NULL,'Please type your travel request.','multi',19,1,'Friendly / application greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (20,'GENERAL','Hello there','Hello! Welcome to Smart Trip.',NULL,'Please type your travel request.','multi',20,1,'Friendly / application greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (21,'GENERAL','Hey there','Hello! Welcome to Smart Trip.',NULL,'Please type your travel request.','multi',21,1,'Friendly / application greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (22,'GENERAL','Hi dear','Hello! Welcome to Smart Trip.',NULL,'Please type your travel request.','multi',22,1,'Friendly / application greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (23,'GENERAL','Hello dear','Hello! Welcome to Smart Trip.',NULL,'Please type your travel request.','multi',23,1,'Friendly / application greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (24,'GENERAL','Hey dear','Hello! Welcome to Smart Trip.',NULL,'Please type your travel request.','multi',24,1,'Friendly / application greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (25,'GENERAL','Dear','Hello! Welcome to Smart Trip.',NULL,'Please type your travel request.','multi',25,1,'Friendly / application greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (26,'GENERAL','Dear assistant','Hello! Welcome to Smart Trip.',NULL,'Please type your travel request.','multi',26,1,'Friendly / application greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (27,'GENERAL','Dear smart trip','Hello! Welcome to Smart Trip.',NULL,'Please type your travel request.','multi',27,1,'Friendly / application greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (28,'GENERAL','Smart trip','Hello! Welcome to Smart Trip.',NULL,'Please type your travel request.','multi',28,1,'Friendly / application greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (29,'GENERAL','Smart trip assistant','Hello! Welcome to Smart Trip.',NULL,'Please type your travel request.','multi',29,1,'Friendly / application greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (30,'HOW_ARE_YOU','How are you','I am fine. What about you?',NULL,'Please type your travel request.','multi',30,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (31,'HOW_ARE_YOU','How r u','I am fine. What about you?',NULL,'Please type your travel request.','multi',31,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (32,'HOW_ARE_YOU','How are u','I am fine. What about you?',NULL,'Please type your travel request.','multi',32,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (33,'HOW_ARE_YOU','How are yu','I am fine. What about you?',NULL,'Please type your travel request.','multi',33,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (34,'HOW_ARE_YOU','How are yuo','I am fine. What about you?',NULL,'Please type your travel request.','multi',34,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (35,'HOW_ARE_YOU','Hw are you','I am fine. What about you?',NULL,'Please type your travel request.','multi',35,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (36,'HOW_ARE_YOU','Hru','I am fine. What about you?',NULL,'Please type your travel request.','multi',36,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (37,'HOW_ARE_YOU','How you doing','I am fine. What about you?',NULL,'Please type your travel request.','multi',37,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (38,'HOW_ARE_YOU','How are you doing','I am fine. What about you?',NULL,'Please type your travel request.','multi',38,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (39,'HOW_ARE_YOU','How do you do','I am fine. What about you?',NULL,'Please type your travel request.','multi',39,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (40,'HOW_ARE_YOU','How is it going','I am fine. What about you?',NULL,'Please type your travel request.','multi',40,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (41,'HOW_ARE_YOU','How going','I am fine. What about you?',NULL,'Please type your travel request.','multi',41,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (42,'HOW_ARE_YOU','Whats up','I am fine. What about you?',NULL,'Please type your travel request.','multi',42,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (43,'HOW_ARE_YOU','What up','I am fine. What about you?',NULL,'Please type your travel request.','multi',43,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (44,'HOW_ARE_YOU','Sup','I am fine. What about you?',NULL,'Please type your travel request.','multi',44,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (45,'HOW_ARE_YOU','Are you there','I am fine. What about you?',NULL,'Please type your travel request.','multi',45,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (46,'HOW_ARE_YOU','You there','I am fine. What about you?',NULL,'Please type your travel request.','multi',46,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (47,'HOW_ARE_YOU','R u there','I am fine. What about you?',NULL,'Please type your travel request.','multi',47,1,'How-are-you / presence variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (48,'HOW_ARE_YOU','Hi how are you','I am fine. What about you?',NULL,'Please type your travel request.','multi',48,1,'Greeting plus how are you','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (49,'HOW_ARE_YOU','Hi how r u','I am fine. What about you?',NULL,'Please type your travel request.','multi',49,1,'Greeting plus short how are you','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (50,'HOW_ARE_YOU','Hii how are you','I am fine. What about you?',NULL,'Please type your travel request.','multi',50,1,'Greeting plus how are you','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (51,'HOW_ARE_YOU','Hii how r u','I am fine. What about you?',NULL,'Please type your travel request.','multi',51,1,'Greeting plus short how are you','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (52,'HOW_ARE_YOU','Hello how are you','I am fine. What about you?',NULL,'Please type your travel request.','multi',52,1,'Greeting plus how are you','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (53,'HOW_ARE_YOU','Hello how r u','I am fine. What about you?',NULL,'Please type your travel request.','multi',53,1,'Greeting plus short how are you','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (54,'HOW_ARE_YOU','Helo how are you','I am fine. What about you?',NULL,'Please type your travel request.','multi',54,1,'Greeting plus how are you','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (55,'HOW_ARE_YOU','Helo how r u','I am fine. What about you?',NULL,'Please type your travel request.','multi',55,1,'Greeting plus short how are you','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (56,'HOW_ARE_YOU','Hey how are you','I am fine. What about you?',NULL,'Please type your travel request.','multi',56,1,'Greeting plus how are you','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (57,'HOW_ARE_YOU','Hey how r u','I am fine. What about you?',NULL,'Please type your travel request.','multi',57,1,'Greeting plus short how are you','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (58,'HOW_ARE_YOU','Hai how are you','I am fine. What about you?',NULL,'Please type your travel request.','multi',58,1,'Greeting plus how are you','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (59,'HOW_ARE_YOU','Hai how r u','I am fine. What about you?',NULL,'Please type your travel request.','multi',59,1,'Greeting plus short how are you','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (60,'TIME_BASED','Good morning','Good morning!',NULL,'Please type your travel request.','multi',60,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (61,'TIME_BASED','Gud morning','Good morning!',NULL,'Please type your travel request.','multi',61,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (62,'TIME_BASED','Gm','Good morning!',NULL,'Please type your travel request.','multi',62,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (63,'TIME_BASED','Morning','Good morning!',NULL,'Please type your travel request.','multi',63,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (64,'TIME_BASED','Good afternoon','Good afternoon!',NULL,'Please type your travel request.','multi',64,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (65,'TIME_BASED','Gud afternoon','Good afternoon!',NULL,'Please type your travel request.','multi',65,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (66,'TIME_BASED','Afternoon','Good afternoon!',NULL,'Please type your travel request.','multi',66,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (67,'TIME_BASED','Good evening','Good evening!',NULL,'Please type your travel request.','multi',67,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (68,'TIME_BASED','Gud evening','Good evening!',NULL,'Please type your travel request.','multi',68,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (69,'TIME_BASED','Evening','Good evening!',NULL,'Please type your travel request.','multi',69,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (70,'TIME_BASED','Good night','Good night!',NULL,'You can come back anytime for your travel booking.','multi',70,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (71,'TIME_BASED','Gud night','Good night!',NULL,'You can come back anytime for your travel booking.','multi',71,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (72,'TIME_BASED','Night','Good night!',NULL,'You can come back anytime for your travel booking.','multi',72,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (73,'TIME_BASED','Gn','Good night!',NULL,'You can come back anytime for your travel booking.','multi',73,1,'Time based greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (74,'THANKS','Thanks','You are welcome.',NULL,'Please type your travel request.','multi',74,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (75,'THANKS','Thanx','You are welcome.',NULL,'Please type your travel request.','multi',75,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (76,'THANKS','Thnx','You are welcome.',NULL,'Please type your travel request.','multi',76,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (77,'THANKS','Thx','You are welcome.',NULL,'Please type your travel request.','multi',77,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (78,'THANKS','Thank you','You are welcome.',NULL,'Please type your travel request.','multi',78,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (79,'THANKS','Thank u','You are welcome.',NULL,'Please type your travel request.','multi',79,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (80,'THANKS','Tq','You are welcome.',NULL,'Please type your travel request.','multi',80,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (81,'THANKS','TY','You are welcome.',NULL,'Please type your travel request.','multi',81,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (82,'THANKS','Thanks dear','You are welcome.',NULL,'Please type your travel request.','multi',82,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (83,'THANKS','Thank you dear','You are welcome.',NULL,'Please type your travel request.','multi',83,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (84,'THANKS','Thanks a lot','You are welcome.',NULL,'Please type your travel request.','multi',84,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (85,'THANKS','Thanx a lot','You are welcome.',NULL,'Please type your travel request.','multi',85,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (86,'THANKS','Thank you so much','You are welcome.',NULL,'Please type your travel request.','multi',86,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (87,'THANKS','Thanks so much','You are welcome.',NULL,'Please type your travel request.','multi',87,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (88,'THANKS','Many thanks','You are welcome.',NULL,'Please type your travel request.','multi',88,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (89,'THANKS','Much appreciated','You are welcome.',NULL,'Please type your travel request.','multi',89,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (90,'THANKS','Appreciated','You are welcome.',NULL,'Please type your travel request.','multi',90,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (91,'THANKS','Shukriya','You are welcome.',NULL,'Please type your travel request.','multi',91,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (92,'THANKS','Shukran','You are welcome.',NULL,'Please type your travel request.','multi',92,1,'Thanks / appreciation variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (93,'FAREWELL','Bye','Goodbye!',NULL,'You can come back anytime for your travel booking.','multi',93,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (94,'FAREWELL','Byee','Goodbye!',NULL,'You can come back anytime for your travel booking.','multi',94,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (95,'FAREWELL','Bye bye','Goodbye!',NULL,'You can come back anytime for your travel booking.','multi',95,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (96,'FAREWELL','Bbye','Goodbye!',NULL,'You can come back anytime for your travel booking.','multi',96,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (97,'FAREWELL','Goodbye','Goodbye!',NULL,'You can come back anytime for your travel booking.','multi',97,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (98,'FAREWELL','See you','See you again.',NULL,'You can come back anytime for your travel booking.','multi',98,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (99,'FAREWELL','See u','See you again.',NULL,'You can come back anytime for your travel booking.','multi',99,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (100,'FAREWELL','C u','See you again.',NULL,'You can come back anytime for your travel booking.','multi',100,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (101,'FAREWELL','Cya','See you again.',NULL,'You can come back anytime for your travel booking.','multi',101,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (102,'FAREWELL','See you later','See you later.',NULL,'You can come back anytime for your travel booking.','multi',102,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (103,'FAREWELL','See u later','See you later.',NULL,'You can come back anytime for your travel booking.','multi',103,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (104,'FAREWELL','Take care','Take care.',NULL,'You can come back anytime for your travel booking.','multi',104,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (105,'FAREWELL','Tc','Take care.',NULL,'You can come back anytime for your travel booking.','multi',105,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (106,'FAREWELL','Talk later','Sure, talk to you later.',NULL,'You can come back anytime for your travel booking.','multi',106,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (107,'FAREWELL','Catch you later','Sure, see you later.',NULL,'You can come back anytime for your travel booking.','multi',107,1,'Farewell variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (108,'INDIA_COMMON','Namaste','Namaste!',NULL,'Please type your travel request.','multi',108,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (109,'INDIA_COMMON','Namste','Namaste!',NULL,'Please type your travel request.','multi',109,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (110,'INDIA_COMMON','Namasthe','Namaste!',NULL,'Please type your travel request.','multi',110,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (111,'INDIA_COMMON','Namaskar','Namaskar!',NULL,'Please type your travel request.','multi',111,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (112,'INDIA_COMMON','Namaskaar','Namaskar!',NULL,'Please type your travel request.','multi',112,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (113,'INDIA_COMMON','Namaskr','Namaskar!',NULL,'Please type your travel request.','multi',113,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (114,'INDIA_COMMON','Pranam','Pranam!',NULL,'Please type your travel request.','multi',114,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (115,'INDIA_COMMON','Pranaam','Pranam!',NULL,'Please type your travel request.','multi',115,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (116,'INDIA_COMMON','Ram Ram','Ram Ram!',NULL,'Please type your travel request.','multi',116,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (117,'INDIA_COMMON','Jai Ram Ji Ki','Jai Ram Ji Ki!',NULL,'Please type your travel request.','multi',117,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (118,'INDIA_COMMON','Jai Shree Ram','Jai Shree Ram!',NULL,'Please type your travel request.','multi',118,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (119,'INDIA_COMMON','Jai Shri Ram','Jai Shri Ram!',NULL,'Please type your travel request.','multi',119,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (120,'INDIA_COMMON','Radhe Radhe','Radhe Radhe!',NULL,'Please type your travel request.','multi',120,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (121,'INDIA_COMMON','Jai Shree Krishna','Jai Shree Krishna!',NULL,'Please type your travel request.','multi',121,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (122,'INDIA_COMMON','Jai Shri Krishna','Jai Shri Krishna!',NULL,'Please type your travel request.','multi',122,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (123,'INDIA_COMMON','Hare Krishna','Hare Krishna!',NULL,'Please type your travel request.','multi',123,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (124,'INDIA_COMMON','Om Shanti','Om Shanti!',NULL,'Please type your travel request.','multi',124,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (125,'INDIA_COMMON','Jai Mata Di','Jai Mata Di!',NULL,'Please type your travel request.','multi',125,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (126,'INDIA_COMMON','Jay Mata Di','Jay Mata Di!',NULL,'Please type your travel request.','multi',126,1,'Common Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (127,'ISLAMIC_GREETING','Assalamualaikum','Wa-Alaikum-As-Salaam.',NULL,'Please type your travel request.','multi',127,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (128,'ISLAMIC_GREETING','Asslamualaikum','Wa-Alaikum-As-Salaam.',NULL,'Please type your travel request.','multi',128,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (129,'ISLAMIC_GREETING','As-salamu alaykum','Wa-Alaikum-As-Salaam.',NULL,'Please type your travel request.','multi',129,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-19 03:00:46');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (130,'ISLAMIC_GREETING','Assalaamualaikum','Wa-Alaikum-As-Salaam.',NULL,'Please type your travel request.','multi',130,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (131,'ISLAMIC_GREETING','Assalam Alaikum','Wa-Alaikum-As-Salaam.',NULL,'Please type your travel request.','multi',131,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (132,'ISLAMIC_GREETING','Assalaam Alaikum','Wa-Alaikum-As-Salaam.',NULL,'Please type your travel request.','multi',132,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (133,'ISLAMIC_GREETING','Salaam','Salaam!',NULL,'Please type your travel request.','multi',133,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (134,'ISLAMIC_GREETING','Salam','Salaam!',NULL,'Please type your travel request.','multi',134,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (135,'ISLAMIC_GREETING','Salam Alaikum','Wa-Alaikum-As-Salaam.',NULL,'Please type your travel request.','multi',135,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (136,'ISLAMIC_GREETING','Salaam Alaikum','Wa-Alaikum-As-Salaam.',NULL,'Please type your travel request.','multi',136,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (137,'ISLAMIC_GREETING','Walaikum Salam','Wa-Alaikum-As-Salaam.',NULL,'Please type your travel request.','multi',137,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (138,'ISLAMIC_GREETING','Walekum Salam','Wa-Alaikum-As-Salaam.',NULL,'Please type your travel request.','multi',138,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (139,'ISLAMIC_GREETING','Walaikum Assalam','Wa-Alaikum-As-Salaam.',NULL,'Please type your travel request.','multi',139,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (140,'ISLAMIC_GREETING','Khuda Hafiz','Khuda Hafiz.',NULL,'You can come back anytime for your travel booking.','multi',140,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (141,'ISLAMIC_GREETING','Allah Hafiz','Allah Hafiz.',NULL,'You can come back anytime for your travel booking.','multi',141,1,'Islamic greeting spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (142,'INDIA_PUNJABI','Sat Sri Akal','Sat Sri Akal!',NULL,'Please type your travel request.','multi',142,1,'Punjabi greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (143,'INDIA_PUNJABI','Sat Shri Akal','Sat Shri Akal!',NULL,'Please type your travel request.','multi',143,1,'Punjabi greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (144,'INDIA_PUNJABI','Sasriakal','Sat Sri Akal!',NULL,'Please type your travel request.','multi',144,1,'Punjabi greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (145,'INDIA_PUNJABI','Waheguru Ji Ka Khalsa Waheguru Ji Ki Fateh','Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh!',NULL,'Please type your travel request.','multi',145,1,'Punjabi greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (146,'INDIA_PUNJABI','Waheguru','Waheguru!',NULL,'Please type your travel request.','multi',146,1,'Punjabi greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (147,'INDIA_GUJARATI','Kem Cho','Majama!',NULL,'Please type your travel request.','multi',147,1,'Gujarati greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (148,'INDIA_GUJARATI','Kem Chho','Majama!',NULL,'Please type your travel request.','multi',148,1,'Gujarati greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (149,'INDIA_GUJARATI','Majama','Majama!',NULL,'Please type your travel request.','multi',149,1,'Gujarati greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (150,'INDIA_GUJARATI','Jay Swaminarayan','Jay Swaminarayan!',NULL,'Please type your travel request.','multi',150,1,'Gujarati greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (151,'INDIA_GUJARATI','Jai Swaminarayan','Jai Swaminarayan!',NULL,'Please type your travel request.','multi',151,1,'Gujarati greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (152,'INDIA_GUJARATI','Jay Jinendra','Jay Jinendra!',NULL,'Please type your travel request.','multi',152,1,'Gujarati greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (153,'INDIA_GUJARATI','Jai Jinendra','Jai Jinendra!',NULL,'Please type your travel request.','multi',153,1,'Gujarati greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (154,'INDIA_SOUTH_COMMON','Vanakkam','Vanakkam!',NULL,'Please type your travel request.','multi',154,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (155,'INDIA_SOUTH_COMMON','Vannakam','Vanakkam!',NULL,'Please type your travel request.','multi',155,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (156,'INDIA_SOUTH_COMMON','Vanakam','Vanakkam!',NULL,'Please type your travel request.','multi',156,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (157,'INDIA_SOUTH_COMMON','Eppadi Irukeenga','I am doing well.',NULL,'Please type your travel request.','multi',157,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (158,'INDIA_SOUTH_COMMON','Nandri','You are welcome.',NULL,'Please type your travel request.','multi',158,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (159,'INDIA_SOUTH_COMMON','Namaskaram','Namaskaram!',NULL,'Please type your travel request.','multi',159,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (160,'INDIA_SOUTH_COMMON','Namaskaaram','Namaskaram!',NULL,'Please type your travel request.','multi',160,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (161,'INDIA_SOUTH_COMMON','Namaskaramu','Namaskaram!',NULL,'Please type your travel request.','multi',161,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (162,'INDIA_SOUTH_COMMON','Ela Unnaru','I am doing well.',NULL,'Please type your travel request.','multi',162,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (163,'INDIA_SOUTH_COMMON','Dhanyavadalu','You are welcome.',NULL,'Please type your travel request.','multi',163,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (164,'INDIA_SOUTH_COMMON','Namaskara','Namaskara!',NULL,'Please type your travel request.','multi',164,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (165,'INDIA_SOUTH_COMMON','Namaskaara','Namaskara!',NULL,'Please type your travel request.','multi',165,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (166,'INDIA_SOUTH_COMMON','Hegiddira','I am doing well.',NULL,'Please type your travel request.','multi',166,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (167,'INDIA_SOUTH_COMMON','Dhanyavadagalu','You are welcome.',NULL,'Please type your travel request.','multi',167,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (168,'INDIA_SOUTH_COMMON','Sughamano','I am doing well.',NULL,'Please type your travel request.','multi',168,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (169,'INDIA_SOUTH_COMMON','Sukhamano','I am doing well.',NULL,'Please type your travel request.','multi',169,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (170,'INDIA_SOUTH_COMMON','Nanni','You are welcome.',NULL,'Please type your travel request.','multi',170,1,'South Indian greeting / spelling variant','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (171,'INDIA_EAST_WEST_COMMON','Nomoskar','Nomoskar!',NULL,'Please type your travel request.','multi',171,1,'Regional Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (172,'INDIA_EAST_WEST_COMMON','Nomoshkar','Nomoskar!',NULL,'Please type your travel request.','multi',172,1,'Regional Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (173,'INDIA_EAST_WEST_COMMON','Kemon Acho','I am doing well.',NULL,'Please type your travel request.','multi',173,1,'Regional Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (174,'INDIA_EAST_WEST_COMMON','Kemiti Achanti','I am doing well.',NULL,'Please type your travel request.','multi',174,1,'Regional Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (175,'INDIA_EAST_WEST_COMMON','Kenekoi Ase','I am doing well.',NULL,'Please type your travel request.','multi',175,1,'Regional Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (176,'INDIA_EAST_WEST_COMMON','Deu Boro Dis Dium','Deu Boro Dis Dium!',NULL,'Please type your travel request.','multi',176,1,'Regional Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (177,'INDIA_EAST_WEST_COMMON','Dev Borem Korum','Dev Borem Korum!',NULL,'Please type your travel request.','multi',177,1,'Regional Indian greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (178,'ARABIC_GULF_COMMON','Marhaba','Marhaba!',NULL,'Please type your travel request.','multi',178,1,'Arabic/Gulf greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (179,'ARABIC_GULF_COMMON','Marhaban','Marhaba!',NULL,'Please type your travel request.','multi',179,1,'Arabic/Gulf greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (180,'ARABIC_GULF_COMMON','Ahlan','Ahlan!',NULL,'Please type your travel request.','multi',180,1,'Arabic/Gulf greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (181,'ARABIC_GULF_COMMON','Ahlan Wa Sahlan','Ahlan Wa Sahlan!',NULL,'Please type your travel request.','multi',181,1,'Arabic/Gulf greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (182,'ARABIC_GULF_COMMON','Sabah Al Khair','Sabah Al Noor!',NULL,'Please type your travel request.','multi',182,1,'Arabic/Gulf greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (183,'ARABIC_GULF_COMMON','Sabah El Khair','Sabah El Noor!',NULL,'Please type your travel request.','multi',183,1,'Arabic/Gulf greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (184,'ARABIC_GULF_COMMON','Masa Al Khair','Masa Al Noor!',NULL,'Please type your travel request.','multi',184,1,'Arabic/Gulf greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (185,'ARABIC_GULF_COMMON','Masa El Khair','Masa El Noor!',NULL,'Please type your travel request.','multi',185,1,'Arabic/Gulf greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (186,'ARABIC_GULF_COMMON','Afwan','Afwan.',NULL,'Please type your travel request.','multi',186,1,'Arabic/Gulf greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (187,'INTERNATIONAL','Bonjour','Bonjour!',NULL,'Please type your travel request.','multi',187,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (188,'INTERNATIONAL','Bonsoir','Bonsoir!',NULL,'Please type your travel request.','multi',188,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (189,'INTERNATIONAL','Salut','Salut!',NULL,'Please type your travel request.','multi',189,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (190,'INTERNATIONAL','Ola','Olá!',NULL,'Please type your travel request.','multi',190,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (191,'INTERNATIONAL','Ciao','Ciao!',NULL,'Please type your travel request.','multi',191,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (192,'INTERNATIONAL','Guten Morgen','Guten Morgen!',NULL,'Please type your travel request.','multi',192,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (193,'INTERNATIONAL','Guten Tag','Guten Tag!',NULL,'Please type your travel request.','multi',193,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (194,'INTERNATIONAL','Guten Abend','Guten Abend!',NULL,'Please type your travel request.','multi',194,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (195,'INTERNATIONAL','Danke','You are welcome.',NULL,'Please type your travel request.','multi',195,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (196,'INTERNATIONAL','Konnichiwa','Konnichiwa!',NULL,'Please type your travel request.','multi',196,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (197,'INTERNATIONAL','Konichiwa','Konnichiwa!',NULL,'Please type your travel request.','multi',197,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (198,'INTERNATIONAL','Arigato','You are welcome.',NULL,'Please type your travel request.','multi',198,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (199,'INTERNATIONAL','Annyeonghaseyo','Annyeonghaseyo!',NULL,'Please type your travel request.','multi',199,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (200,'INTERNATIONAL','Sawasdee','Sawasdee!',NULL,'Please type your travel request.','multi',200,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (201,'INTERNATIONAL','Xin Chao','Xin Chao!',NULL,'Please type your travel request.','multi',201,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (202,'INTERNATIONAL','Ni Hao','Ni Hao!',NULL,'Please type your travel request.','multi',202,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (203,'INTERNATIONAL','Obrigado','You are welcome.',NULL,'Please type your travel request.','multi',203,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
INSERT INTO `greeting_mst` (`greeting_id`, `greeting_type`, `greeting_msg`, `reply_msg`, `prefix_msg`, `suffix_msg`, `lang_code`, `display_order`, `is_active`, `remarks`, `created_at`, `updated_at`) VALUES (204,'INTERNATIONAL','Obrigada','You are welcome.',NULL,'Please type your travel request.','multi',204,1,'International greeting','2026-06-16 21:23:51','2026-06-16 21:23:51');
/*!40000 ALTER TABLE `greeting_mst` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-06-26 19:27:23
